// Do not edit this file. Instead, make a copy of it and rename it to "env.js"
// then custom your own environment config there!

const path = require('path')

module.exports = {
    // develop settings
    mode:           'development',              // 'development' or 'production' 
    watch:          true,                       // watch files or not when "npm run build"
    useHTTPS:       false,                      // use http or https server
    openBrowser:    true,                       // open browser automatically when running develop tools
    vueVersion:     'vue/dist/vue.esm.js',      // switch vue version

    // port
    nodeServerPort:         '2018',             // port of express server
    webpackServerPort:      '8080',             // port of webpack dev server
    browserSyncServerPort:  '3000',             // port of browser-sync server

    // path of directories
    keyDir:     path.resolve( process.cwd(), 'key' ),       // folder for key files
    productDir: path.resolve( process.cwd(), 'product' ),   // folder for built files
}
